### ISSUE TITLE
Accented characters in the JSON file

### ISSUE THREAD

**Issue by lucprefontaine** [innovara/autoreply#1]
Hi,

I hit an issue when using accented characters in the json file:

with open(os.path.expanduser('~') + '/autoreply.json', 'r') as json_file:
    data = json.load(json_file)

should be replaced by this:

with open(os.path.expanduser('~') + '/autoreply.json', 'r', encoding='utf-8') as json_file:
    data = json.load(json_file)

Otherwise the json parsing fails.

I also added:

def load_json():
  with open(os.path.expanduser('~') + '/autoreply.json', 'r', encoding='utf-8') as json_file:
    data = json.load(json_file)
  return data

to replace all the calls to load the json file

and:
  if '-l' in sys.argv[1:]:
    print(load_json())
    exit()

To test if it's loadable.

Nice script. About to leave for a few days and I was wondering how to setup an auto reply on my postfix server.
No time to send you a pull request though :)

**Comment by innovara** [comment]
Hi,

0b924122ccaed3ef0f8e7ca6b85e1bfff72c31d8 fixes the issue reported re special characters

I've added the -l option to show the content configuration file, but with a slightly different approach.

Re the use of load_json(), there is open_json() already. I am not sure what you mean by 'all calls to load the json file' as this is done with open_json() already. Am I missing any instance where open_json() could be used and it's not?

Thanks

**Comment by lucprefontaine** [comment]
Hi,

I superseded open_json. Went for a shortcut from the moment load_json worked.

I was in a hurry 😌

Luc P.
