### ISSUE TITLE
If an version of autoreply prior to the new ssl setting is upgraded, autoreply stops working.

### ISSUE THREAD

**Issue by oerjann** [innovara/autoreply#14]
if the new new setting 'ssl' is not present in the configuration file autoreply does not work

Command died with status 1:
    "/opt/autoreply/autoreply.py". Command output: Traceback (most recent call
    last):   File "/opt/autoreply/autoreply.py", line 314, in <module>
    main()   File "/opt/autoreply/autoreply.py", line 309, in main
    autoreply(sender, recipients, original_msg, original_id)   File
    "/opt/autoreply/autoreply.py", line 238, in autoreply
    send_email(message)   File "/opt/autoreply/autoreply.py", line 133, in
    send_email     if settings['ssl'] == True: KeyError: 'ssl'

**Comment by innovara** [comment]
Thanks for reporting the issue. I'm in two minds about this one. One one hand, I would like to avoid as many crashes as possible. On the other hand, I would like to implement changes to the configuration file as and when needed without the burden of having to think if someone is using an older version of it. For the time being I will document that the expected upgrade path is a newly generated config file and changes ported over to it.

**Comment by oerjann** [comment]
Thank you! I have no problem to understand that you don't want the extra work with backward combability. The updated documentation will help when running into this. Great work with this script!
