### ISSUE TITLE
Missing starttls 

### ISSUE THREAD

**Issue by BibleProg** [innovara/autoreply#2]
Hey, I had this error : `smtplib.SMTPSenderRefused: (530, b'5.7.0 Must issue a STARTTLS command first', test@test.com')`

And i get rid of it by adding this line : `mail_server.starttls()` in `send_email()`

**Comment by innovara** [comment]
I'd make that conditional and add a setting in autoreply.json i.e. starttls:true to cover both use cases. Would you be able to test that change if I made it?

**Comment by BibleProg** [comment]
Yeah of course ! I customized your code to adapt it for my needed, there it is ! I added SMTP connection, html message with image, also i added some header to tell this is an autoreply mail (https://www.rfc-editor.org/rfc/rfc3834). There where another loop problem with other auto-response i added a detector and dont send autoreply when i detected it.
[autoreply.zip](https://github.com/innovara/autoreply/files/10827644/autoreply.zip)

**Comment by innovara** [comment]
Can you tell me a little bit more about the loop that you prevent with `and (not re.search("^.*(noreply|nepasrepondre)@.*$",sender)):`? Is it two accounts auto replying to each other and creating a loop?

I've added support for STARTTLS and SMTP authentication. My tests indicate that this part is working fine and I've been able to use `smtp.office365.com` with port `587` and `STARTTLS` encryption. Be aware that the structure of `autoreply.json` has changed a bit.

I'll look into the html email and the image another time. I'd like to keep both options so my implementation would be slightly different.

**Comment by BibleProg** [comment]
Yep this is that, there was 2 mail server with autoreply and when i came back to work at 8 am i seen something like 100 emails in the mailbox. si i added this detection + `if (original_msg['Auto-Submitted'] == "no") or (original_msg['X-Autoreply'] != "yes"):` for autoreply mail forged with the rfc3834. To see header of an automatic mail try to activate vaccation mod on gmail, and see the headers of the vaccation mail.

**Comment by BibleProg** [comment]
I will test your change on monday

**Comment by BibleProg** [comment]
The news settings work perfectly!

**Comment by innovara** [comment]
Thank you. I've added some autoreply checks and other recommendations listed here: https://www.arp242.net/autoreply.html

I also encountered some encoding issues while testing so I've made changes to how the original email is reinjected which I believe makes more sense. The email is now returned to Postfix in binary and it's identical to what the script received in the first place.
