### ISSUE TITLE
problem with emails from microsoft

### ISSUE THREAD

**Issue by mrki01** [innovara/autoreply#4]
I installed autoreply.py and it works fine. Except when someone who have email on microsoft sends mail.

Sender receives error message instead of autoreply. 

Here is what sender receives:
 Command died with status 1:
>     "/opt/autoreply/autoreply.py". Command output: Traceback (most recent call
>     last):   File "/opt/autoreply/autoreply.py", line 241, in <module>
>     main()   File "/opt/autoreply/autoreply.py", line 237, in main
>     autoreply(sender, recipients, original_id)   File
>     "/opt/autoreply/autoreply.py", line 165, in autoreply     message =
>     generate_email(   File "/opt/autoreply/autoreply.py", line 74, in
>     generate_email     message['In-Reply-To'] = original_id   File
>     "/usr/lib/python3.9/email/message.py", line 409, in __setitem__
>     self._headers.append(self.policy.header_store_parse(name, val))   File
>     "/usr/lib/python3.9/email/policy.py", line 146, in header_store_parse
>     raise ValueError("Header values may not contain linefeed " ValueError:
>     Header values may not contain linefeed or carriage return characters

regards

**Comment by innovara** [comment]
When you say 'email on microsoft', do you mean they are using a Microsoft email account like Office 365 or Outlook.com or do you mean that they are sending the email from Microsoft Outlook, the application?

Either way, the error is not coming from `autoreply.py` as such but email, the Python module. More specifically, `/usr/lib/python3.9/email/policy.py` has found a linefeed or carriage return character in the header which is illegal. Can you share the content of your `autoreply.json` to see if you have added anything that could be causing this? Please censor credentials and identifying information.

**Comment by mrki01** [comment]
They are using Microsoft accounts (Office 365). I get the same error with my outlook.com mail.

My autoreply.json is here:
{
    "logging": false,
    "SMTP": "localhost",
    "port": 25,
    "starttls": false,
    "smtpauth": false,
    "username": "autoreply",
    "password": "xxxxxxxxx",
    "autoreply": [
        {   
            "email": "test@malvazija.krs.hr",
            "reply-to": "nobody@krs.hr",
            "subject": "Automatski odgovor",
            "body": "qui tacet consentire videtur"
        },
        {   
            "email": "nabava@malvazija.krs.hr",
            "reply-to": "nobody@krs.hr",
            "subject": "Automatski odgovor",
            "body": "qui tacet consentire videtur"
        }
    ]
}

regards

**Comment by mrki01** [comment]
Did you check my configuration?

Is it possible to solve this problem?

Autoreply is working fine with all mails, except that sent from microsoft servers :(

regards

**Comment by innovara** [comment]
I checked the configuration and it looks fine. In this regard, it's best to use code blocks in your posts on GitHub to embed config files, logs, code, etc.

I also checked various emails from Microsoft and the header that is triggering the error doesn't look any different to those of other emails.

It's possible that there is a bug on either `/usr/lib/python3.9/email/message.py` or `/usr/lib/python3.9/email/policy.py` which belong to the mail Python module of your distribution. I wanted to check if I could replicate the problem on another distribution but unfortunately I don't have a running configuration so I needed to create that first and I didn't have time.

Meanwhile, what distro are you using? Is it Ubuntu 22.04 or something else?

**Comment by mrki01** [comment]
I am using Debian 11.

I can check on Debian 10 server.

regards

**Comment by innovara** [comment]
If you can do that, it would be very helpful. Thanks

**Comment by mrki01** [comment]
I installed autoreply on debian 10 server, but there is the same problem:

 Command died with status 1:
    "/opt/autoreply/autoreply.py". Command output: Traceback (most recent call
    last):   File "/opt/autoreply/autoreply.py", line 241, in <module>
    main()   File "/opt/autoreply/autoreply.py", line 237, in main
    autoreply(sender, recipients, original_id)   File
    "/opt/autoreply/autoreply.py", line 171, in autoreply     recipient['body']
    File "/opt/autoreply/autoreply.py", line 74, in generate_email
    message['In-Reply-To'] = original_id   File
    "/usr/lib/python3.7/email/message.py", line 409, in __setitem__
    self._headers.append(self.policy.header_store_parse(name, val))   File
    "/usr/lib/python3.7/email/policy.py", line 145, in header_store_parse
    raise ValueError("Header values may not contain linefeed " ValueError:
    Header values may not contain linefeed or carriage return characters

:(

regards

**Comment by innovara** [comment]
I've been able to replicate the problem. It seems that Microsoft adds a new character somewhere. I'll see what I can do to remove that.

**Comment by innovara** [comment]
Check now. I've added some parsing on Message-Id to remove linefeed or carriage return characters and my test email worked.

I plan to add html email support. Hopefully soon.

**Comment by mrki01** [comment]
> Check now. I've added some parsing on Message-Id to remove linefeed or carriage return characters and my test email worked.

it's working!

thank you

regards
